name: battery-system
channels:
  - defaults
dependencies:
  - ipykernel
  - jupyter
  - pip
  - python=3.8.3
  - scikit-learn
  - scipy
  - deprecated
  - tabulate
  - matplotlib
  - pip:
    - numpy
    - tensorflow
    - cond-rnn